### PR TITLE
Updated testing with local compute of 3D DFT

### PR DESCRIPTION
**Pull request by elliottbinder**
1D test output should be more readable.
Added option for first element check or local compute check for correctness. Local compute test would require all inputs and outputs to reside in a single tasks memory, so should only be expected to work on smaller volumes. Currently only checking when all inputs are less than 32.
Updated the distributed code to include an inverse embedded path.

### CODE REVIEW

**Comment by broderickpt** [comment]
I’m going to merge this as I don’t see that it harms anything.

However, please explain what this output means:

 

srun -N 1 -n 1 -t2:00 -A CSC304_crusher ./test3DDFT_mpi_1D 32 32 32 1 0 0 1 1

non-supported fixed library transform

non-supported fixed library transform

non-supported fixed library transform

32,32,32,1,1,,inv,complex,first_elem,0.772004,0

 

 

Patrick Broderick

(412) 608-7202

 ***@***.***> ***@***.***

 

“Chains of habit are too light to be felt until they are too heavy to be broken.” - Warren Buffett

 

 

From: elliottbinder ***@***.***> 
Sent: Friday, August 25, 2023 17:19
To: spiral-software/fftx ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [spiral-software/fftx] Updated testing with local compute of 3D DFT (PR #166)

 

1D test output should be more readable.
Added option for first element check or local compute check for correctness. Local compute test would require all inputs and outputs to reside in a single tasks memory, so should only be expected to work on smaller volumes. Currently only checking when all inputs are less than 32.
Updated the distributed code to include an inverse embedded path.

  _____  


You can view, comment on, or merge this pull request online at:


  https://github.com/spiral-software/fftx/pull/166


Commit Summary


*	9b6db43 <https://github.com/spiral-software/fftx/pull/166/commits/9b6db433b89b91e2fcf0b0641cc39a1cd66b68a3>  add local test, add inv embedding
*	cd28c90 <https://github.com/spiral-software/fftx/pull/166/commits/cd28c90194d2265d2bbfb349fa2578132c41feb9>  add macro for distributed testing


File Changes 


(6 <https://github.com/spiral-software/fftx/pull/166/files>  files)

*	M examples/3DDFT_mpi/test3DDFT_mpi_1D.cpp <https://github.com/spiral-software/fftx/pull/166/files#diff-be12c92c85936a20c607e4b9bd2a8be88fe54039eb94a6a677ecfb1a512b962c>  (732) 
*	M src/library/lib_fftx_mpi/fftx_1d_mpi.cpp <https://github.com/spiral-software/fftx/pull/166/files#diff-287aebc66b383f3d131f39f34d5721e1c2f5ce4fd708521cd22deaa20becb7f4>  (141) 
*	M src/library/lib_fftx_mpi/fftx_1d_mpi_default.cpp <https://github.com/spiral-software/fftx/pull/166/files#diff-c384fdc91a76ac9cbd3dfd45d156904d392c5260f932e4f63b2f300c4c9be26c>  (80) 
*	M src/library/lib_fftx_mpi/fftx_gpu.cpp <https://github.com/spiral-software/fftx/pull/166/files#diff-fb167df432a382b2fca2df3f46917a2f01d548b92e357c17ef320f848168ff0f>  (23) 
*	M src/library/lib_fftx_mpi/fftx_mpi.cpp <https://github.com/spiral-software/fftx/pull/166/files#diff-827bbe707a34e9c7b167cffc872174c9493e33b261a13f5fbd9e96c652c527f9>  (4) 
*	M src/library/lib_fftx_mpi/fftx_mpi.hpp <https://github.com/spiral-software/fftx/pull/166/files#diff-f54d74824fb0cafaa530192797cd8a6e2a8835d79fbe4a8442447b5eda0d4190>  (2) 


Patch Links:


*	https://github.com/spiral-software/fftx/pull/166.patch
*	https://github.com/spiral-software/fftx/pull/166.diff

**Comment by elliottbinder** [comment]
The "non-supported fixed library transform" text is not from my side. We can check with Sanil. The last line gives the problem size (M, N, K, batch), the input configuration (not-embedded, inverse transform, complex), the test being used (check the first element for correctness), the execution time (.77 seconds), and the result of the correctness check (0 indicating incorrect).

**Comment by sr7cb** [comment]
The non-supported fixed library transform is from FFTX RTC. I have not
tested the inverse transform thoroughly so being incorrect is expected.
When this is integrated I can take a look and try and fix the problem.

**Comment by elliottbinder** [comment]
I will also note there are some combinations of inputs and launch configurations I'm working on supporting. I see that you are launching with 1 MPI rank, which I have not tested much. I usually use minimum 2 ranks. Currently, ensuring that both M and K are divisible by the number of MPI ranks being used should be correct in most if not all cases.

**Pull request merged**
