### PR TITLE
Larger batch size support for spiral distributed backend

### PR DESCRIPTION
**Pull request by sr7cb**
Stress testing sizes is required

### CODE REVIEW

**Review by broderickpt — CHANGES_REQUESTED** [review]
The code builds but when I try to test, I get errors:

srun -N 1 -n 1 -t1:00 -A CSC304_crusher ./test3DDFT_mpi_1D 128 128 128 4 0 1 1 3 1
Problem size: 128 x 128 x 128
Batch size  : 4
Complex     : Yes
Embedded    : No
Direction   : Forward
MPI Ranks   : 1
Times       : 
non-supported fixed library transform

main error: hipErrorInvalidConfiguration failed with error invalid configuration argument
srun: error: crusher012: task 0: Exited with exit code 1

Similar failures for batch = 16.  For real data (it uses the vendor libraries) things succeed.

What batch sizes are expected to work and what (if any) other parameters are needed?

**Comment by sr7cb** [comment]
This error is usually the result of a spiral kernel launch parameter configuration issue. I hadn't tested batch sizes larger than 8 or cube sizes larger than 64^3.

**Comment by sr7cb** [comment]
My run seems to work see my output:
sanilrao@login15 ~/multi-branch-fftx/build/examples/3DDFT_mpi (spiral-mpi) $ srun -N 1 -n 1 -t1:00 -A CSC304 ./test3DDFT_mpi_1D 128 128 128 4 0 1 1 3 1
srun: job 1428729 queued and waiting for resources
srun: job 1428729 has been allocated resources
Problem size: 128 x 128 x 128
Batch size  : 4
Complex     : Yes
Embedded    : No
Direction   : Forward
MPI Ranks   : 1
Times       : 
non-supported fixed library transform
non-supported fixed library transform
non-supported fixed library transform
        Trial 0: 1.28115 seconds
non-supported fixed library transform
non-supported fixed library transform
non-supported fixed library transform
        Trial 1: 1.19141 seconds
non-supported fixed library transform
non-supported fixed library transform
non-supported fixed library transform
        Trial 2: 1.18861 seconds
Correct     : Yes

**Review by broderickpt — APPROVED** [review]

**Comment by broderickpt** [comment]
In light of the prior comment, I did a clean, complete rebuild and tested:

Cube sizes:	64^3, 128^3, 256^3
Direction: 	Forward & Inverse
Batch sizes:	4, 8, 16
Total # tests = 18

All passed OK.

**Pull request merged**
